### DISCUSSION TITLE
position: sticky funktioniert nicht

### DISCUSSION THREAD

**Discussion by AHen-C0de** [neuefische/questions#121] [Web] [answered]
_position: sticky_ doesn't work in _ul_ element. Why?

**Expected:** 
Navbar should always be at the bottom.

**Actual:**
1. Navbar is not at the bottom.
2. Navbar doesn't stay at the bottom while scrolling.

**live example:**
https://codepen.io/flurryc0de/pen/abYgrXZ

## html

```html
<footer>
      <nav>
        <ul class="nav--wrapper">
          <li>
            <img src="./images/home.png" />
          </li>
          <li>
            <img src="./images/bookmarks.png" />
          </li>
          <li>
            <img src="./images/profile.png" />
          </li>
        </ul>
      </nav>
    </footer>
```

## styles.css
```css
.nav--wrapper {
  display: flex;
  justify-content: space-evenly;
  align-items: center;
  position: sticky;
  bottom: 0;
  margin: 0;
  padding: 0;
  width: 100%;
  list-style: none;
  padding: 10px 0 10px 0;
  background-color: coral;
}

nav img {
  height: 2.2rem;
}
```

![Screenshot 2022-08-29 at 13 50 05](https://user-images.githubusercontent.com/100531381/187194751-35194248-ebea-4d48-a385-3c15fc694700.png)

**Comment by philmetscher** [comment, marked as answer]
1. Problem: Das HTML ist wahrscheinlich nicht groß genug. Um das zu korrigieren kannst du das CSS hinzufügen:
```css
html, body {
  min-height: 100%;
}
```
2. Problem: position: sticky richtet sich nach dem parent Element aus. Da hier `nav` das parent-element ist klebt  `.nav-wrapper` an dem `nav` unten dran
