### DISCUSSION TITLE
Link does not share the background color of ancestor

### DISCUSSION THREAD

**Discussion by kornrumpfl** [neuefische/questions#140] [Web] [answered]
When changing the background color of the ul element, how do i include the links?

```html
<ul class="contactinfo">
    <li><a href="https://www.linkedin.com/in/luizkornrumpf">LinkeIn</a></li>
    <li><a href="">Contact</a></li>
</ul>
```
 
CSS
```css
* {
  box-sizing: border-box;
  background-color: #E5E3C9;
}
.contactinfo{
    display:flex;
    flex-flow: row wrap;
    justify-content: flex-end;
    list-style: none;
    margin: 0; 
    background: deepskyblue;
}
```

Example: https://codepen.io/LuizKornrumpf/pen/dyePjPP

![Screenshot 2022-09-05 at 13 47 37](https://user-images.githubusercontent.com/112061209/188441964-179a9ac2-7f5a-4e6b-9e98-e3c602a9bd6a.png)

**Comment by ahohnsen** [comment, marked as answer]
Hey,

With the universal selector (`*`) you are currently setting the `background-color` for every single element to `#E5E3C9`.

```css
* {
  background-color: #E5E3C9;
}
```

I recommend giving the body a background-color instead, so that you can style all elements individually. 

```css
body {
  background-color: #E5E3C9;
}
```

If you want to apply more styles to your links, you can do so with a class selector:

```css
.link {
  text-decoration: none;
  padding: 2px;
}
```
Please remember to add this class to the link-tag (`<a>`) in your html. 🙂 

... or type selector:
```css
a {
  text-decoration: none;
  padding: 2px;
}
```
