### DISCUSSION TITLE
Linter - webkit-box

### DISCUSSION THREAD

**Discussion by SLS-BLN** [neuefische/questions#37] [Web] [answered]
Der Linter wirft mir einen Fehler aus, wenn ich `-webkit-box` und `-webkit-box-orient` nutze. Hat jemand eine Idee, was in diesem Fall zu tun ist? Bei der Recherche habe ich keine Lösung gefunden.

<img width="450" alt="Screenshot 2022-08-01 at 15 46 44" src="https://user-images.githubusercontent.com/99472170/182179288-54c3d919-1a7f-4ac4-8593-8a8c96accb4a.png">

**Warum ist das wichtig?**
Ich möchte den Text in dieser Box so anpassen, dass am Ende "..." zu sehen sind, wenn der Platz für den Text nicht ausreicht.

<img width="305" alt="Screenshot 2022-08-01 at 16 51 14" src="https://user-images.githubusercontent.com/99472170/182177702-ddd09468-0a68-4fc0-b9b9-6987c0cfd19d.png">

Das CSS sieht wie folgt aus:

```
p {
    font-size: 1.2rem;
    line-height: 1.2;
    display: -webkit-box;
    -webkit-line-clamp: var(--line-clamp, 6);
    -webkit-box-orient: vertical;
    word-break: var(--word-break, 'none');
    overflow: hidden;
    hyphens: auto;
    text-align: var(--align, left);

    --is-single-line: 1 - clamp(0, calc(var(--line-clamp) - 1), var(--line-clamp));
    --delay: calc(-1s * (var(--is-single-line, 1) - 1));

    animation: states 1s var(--delay) paused;
  }
```

Und hier ist noch der Link zum aktuellen branch `dev-blog-2`im [Capstone Project](https://github.com/SLS-BLN/Capstone-Project/tree/blog-dev-2)

**Comment by pixelass** [comment, marked as answer]
`-webkit-` heisst dass das nur auf webkit Browsern oder Browsern mit webkit support funktioniert, daher beschwert sich hier Stylelint. Heutzutage sollte das jedoch in allen browsern klappen (alle neuen Browser haben das feature freigeschaltet, siehe https://caniuse.com/?search=line-clamp, bzw. https://caniuse.com/mdn-css_properties_-webkit-line-clamp), jedoch weiss das Stylelint nicht.

Hier kannst du "als Ausnahme" Stylelint ausschalten (siehe: https://stylelint.io/user-guide/ignore-code/)

```css
p {
    /* ...rest of the css*/

    /* stylelint-disable value-no-vendor-prefix property-no-vendor-prefix */
    display: -webkit-box;
    -webkit-line-clamp: var(--line-clamp, 6);
    -webkit-box-orient: vertical;
    /* stylelint-enable value-no-vendor-prefix property-no-vendor-prefix */
    

    /* ...rest of the css*/
  }
```

Oder spezificscher (empfohlen)

```css
p {
    /* ...rest of the css*/

    display: -webkit-box; /* stylelint-disable-line value-no-vendor-prefix  */
    -webkit-line-clamp: var(--line-clamp, 6); /* stylelint-disable-line property-no-vendor-prefix */
    -webkit-box-orient: vertical; /* stylelint-disable-line property-no-vendor-prefix */

    /* ...rest of the css*/
  }
```
