### DISCUSSION TITLE
CSS: How to fix individual positioning of bookmark buttons?

### DISCUSSION THREAD

**Discussion by pixelass** [neuefische/questions#456] [Web]
> THIS IS A DEMO. Feel free to answer this question or use it as an example.

I am trying to position my bookmarks in the top left corner of each card but for some reason the are always in the top left corner of my app.

![expected-actual-position-absolute](https://user-images.githubusercontent.com/1148334/213164512-2f4aa4b7-03bc-4ae6-a7cf-acc8c5c66c03.png)

Here is an isolation of this problem in a codepen: https://codepen.io/dekk/pen/bGjoXwd

```html
<div class="card">
  <div class="bookmark"></div>
</div>
<div class="card">
  <div class="bookmark"></div>
</div>
<div class="card">
  <div class="bookmark"></div>
</div>
```

```css
.card {
  border-radius: 10px;
  background: yellow;
  height: 200px;
  width: 200px;
  margin: 20px;
}

.bookmark {
  position: absolute;
  top: 0;
  left: 0;
  height: 20px;
  width: 20px;
  background: red;
}


```
