### DISCUSSION TITLE
CSS transform doesn't work properly on Smartphones

### DISCUSSION THREAD

**Discussion by YuriPadilla** [neuefische/questions#472] [Web] [answered]
Hello! I want to make a TOAST Notification. It works well on Desktop's Screen, but on Smartphone's Screen doesn't work.

Here is a picture of the problem (only with a smartphone's Screen):

![Bildschirmfoto 2023-01-27 um 13 24 44](https://user-images.githubusercontent.com/53151968/215086513-d3d431e5-07c7-4209-bc70-1e9d76fb0f62.png)

The Toast message should be first hidden.

Here is my CSS:
```CSS
.toast {
  position: absolute;
  top: 80px;
  right: 25px;
  padding: 1rem 2rem;
  border: none;
  font-size: 0.8rem;
  background: rgb(81, 229, 106);
  color: rgb(0 0 0 / 0.8);
  border-radius: 15px;
  box-shadow: rgba(0, 0, 0, 0.12) 3px 5px 5px, rgba(0, 0, 0, 0.24) 0px 1px 2px;
  transform: translateX(150%);
  overflow: hidden;
}

.toast.enter {
  transform: translateX(0);
  transition: transform 1s cubic-bezier(0, 0.79, 1, 1.02);
}

.toast.exit {
  transform: translateX(150%);
  transition: transform 1s cubic-bezier(0, -0.03, 1, 0.41);
}
```
Do anyone of you have an idea how to solve the problem???

Thanks a lot!!!  :)
